exclude: 'third_party/*'

repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: flake8
    additional_dependencies: [
      flake8-bugbear==20.1.4,
      flake8-builtins==1.5.3,
      flake8-comprehensions==3.2.3,
      flake8-docstrings==1.5.0,
      flake8-import-order==0.18.1,
      flake8-tidy-imports==4.1.0,
      flake8==3.8.3
    ]
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/pyupgrade
  rev: v1.13.0
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.5.1
  hooks:
  - id: python-check-mock-methods
  - id: python-use-type-annotations
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 9feadeb
  hooks:
  - id: mypy
    args: [
      --ignore-missing-imports,
      --warn-no-return,
      --warn-redundant-casts,
      --disallow-incomplete-defs,
      --check-untyped-defs
    ]
